version: "3.9"

services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: fastapi_app
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    command: uv run celery -A worker.celery_app worker --loglevel=info
