[project]
name = "celery-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.5.3",
    "fastapi>=0.119.1",
    "uvicorn>=0.38.0",
]
